[build]
builder = "RAILPACK"
buildCommand = "pip install -r requirements.txt"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "gunicorn DarbarBootsPro.wsgi:application --bind 0.0.0.0:$PORT --timeout 120"
postDeployCommand = "python manage.py migrate --noinput && python manage.py collectstatic --noinput"
sleepApplication = false
