[build]
builder = "RAILPACK"
buildCommand = "pip install -r requirements.txt && python manage.py collectstatic --noinput"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "python manage.py migrate --noinput && gunicorn DarbarBootsPro.wsgi:application --bind 0.0.0.0:$PORT --timeout 120"
sleepApplication = false
